---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openstad.cdn.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  reactUrl: {{ .Values.secrets.cdn.reactUrl | default "" | b64enc }}
  reactDomUrl: {{ .Values.secrets.cdn.reactDomUrl | default "" | b64enc }}
