{{- if eq (include "openstad.ingress.type" .) "traefik" -}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openstad.fullname" . }}-security-headers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
spec:
  headers:
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "SAMEORIGIN"
      X-Xss-Protection: "1"
      Referrer-Policy: "same-origin"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openstad.fullname" . }}-security-headers-hsts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openstad.fullname" . }}-security-headers-noindex
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openstad.fullname" . }}-body-size-limit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: 134217728
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "openstad.fullname" . }}-www-redirect
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: "^https?://www\\.(.*)"
    replacement: "https://${1}"
    permanent: true
{{- end -}}
