---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openstad.cms.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "openstad.cms.fullname" . }}-deployment
spec:
  replicas: {{ .Values.cms.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.cms.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.cms.label }}
    spec:
      containers:
      - name: {{ template "openstad.cms.fullname" . }}
        image: {{ .Values.cms.deploymentContainer.image }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: {{ .Values.cms.service.httpPort }}
            name: http
        env:
          - name: PORT
            value: "{{ .Values.cms.service.httpPort }}"
          - name: API_URL
            value: https://{{ template "openstad.api.url" . }}
          - name: API_URL_INTERNAL
            value: http://{{ printf "%s.%s.svc.cluster.local:%d" (include "openstad.api.fullname" .) .Release.Namespace (.Values.api.service.httpPort | int) }}
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                key: apiKey
                name: {{ template "openstad.cms.secret.fullname" . }}
          - name: OVERWRITE_URL
            value: https://{{ template "openstad.cms.url" . }}
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                key: mongodbUri
                name: {{ template "openstad.cms.secret.fullname" . }}
          - name: MONGODB_PREFIX
            valueFrom:
              secretKeyRef:
                key: mongodbPrefix
                name: {{ template "openstad.cms.secret.fullname" . }}
          - name: REACT_CDN
            valueFrom:
              secretKeyRef:
                key: reactUrl
                name: {{ template "openstad.cdn.secret.fullname" . }}
          - name: REACT_DOM_CDN
            valueFrom:
              secretKeyRef:
                key: reactDomUrl
                name: {{ template "openstad.cdn.secret.fullname" . }}
          - name: CMS_DEFAULTS
            value: "{}"

          - name: NODE_ENV
            value: production

          - name: DISABLE_RATE_LIMITER
            value: {{ .Values.cms.disableRateLimiter | default "false" | quote }}

          - name: DISABLE_WIDGET_PREVIEW
            value: {{ .Values.cms.disableWidgetPreview | default "false" | quote }}
{{- if eq .Values.cms.useS3 "true" }}
          - name: APOS_S3_ENDPOINT
            valueFrom:
              secretKeyRef:
                key: cmsEndpoint
                name: {{ template "openstad.s3.secret.fullname" . }}

          - name: APOS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                key: cmsBucket
                name: {{ template "openstad.s3.secret.fullname" . }}

          - name: APOS_S3_REGION
            valueFrom:
              secretKeyRef:
                key: cmsRegion
                name: {{ template "openstad.s3.secret.fullname" . }}

          - name: APOS_S3_KEY
            valueFrom:
              secretKeyRef:
                key: cmsKey
                name: {{ template "openstad.s3.secret.fullname" . }}

          - name: APOS_S3_SECRET
            valueFrom:
              secretKeyRef:
                key: cmsSecret
                name: {{ template "openstad.s3.secret.fullname" . }}
{{- end }}
          # Inject extra environment variables
          {{- if .Values.cms.extraEnvVars }}
          {{- include "common.tplvalues.render" (dict "value" .Values.cms.extraEnvVars "context" $) | nindent 10 }}
          {{- end }}
        {{- if .Values.cms.customCommand }}
        command: {{ toYaml .Values.cms.customCommand | nindent 12 }}
        {{- end }}
        {{- if .Values.cms.customWorkingDir }}
        workingDir: {{ .Values.cms.customWorkingDir }}
        {{- end }}
        resources:
{{ toYaml .Values.cms.resources | indent 12 }}
        volumeMounts:
          - mountPath: /tmp
            name: tmp-dir
          - mountPath: /opt/openstad-headless/apps/cms-server/data/temp
            name: temp-dir
{{- if ne .Values.cms.useS3 "true" }}
          - mountPath: {{ .Values.cms.volumes.data.mountPath | default "/opt/openstad-headless/apps/cms-server/public/uploads/attachments" }}
            name: data-vol
{{- end }}
      volumes:
        - name: tmp-dir
          emptyDir: {}
        - name: temp-dir
          emptyDir: {}
{{- if ne .Values.cms.useS3 "true" }}
        - name: data-vol
          persistentVolumeClaim:
            claimName: cms-data-claim
{{- end }}
